extern GdkPixbuf *pix_book;
extern GdkPixbuf *pix_128;
extern GdkPixbuf *pix_48;
extern GdkPixbuf *pix_32;
extern GdkPixbuf *pix_hop;
extern GdkPixbuf *pix_purple;
extern GdkPixbuf *pix_red;
extern GdkPixbuf *pix_op;
extern GdkPixbuf *pix_voice;
extern GdkPixbuf *pix_hilite;
extern GdkPixmap *pixmap_load_from_file (char *file);
extern void pixmaps_init (void);
