DATA = 	book.png		\
	status/hop.png		\
	status/op.png		\
	status/purple.png	\
	status/red.png		\
	status/voice.png	\
    highlight.png		\
    128.png				\
    48.png				\
    32.png				\
    16.png				\

include ../../buildsys.mk

PACKAGE = conspire/pixmaps


